services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php74-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "8083:80"
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_DATABASE: mydb
      DB_USERNAME: myuser
      DB_PASSWORD: mypass
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: postgres16
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data:
